services:
  neo4j:
    image: neo4j:5.20
    container_name: neo4j-graphrag_tsai
    ports:
      - "17474:7474"   # browser
      - "17687:7687"   # bolt
    environment:
      - NEO4J_AUTH=neo4j/password123
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
      - NEO4JLABS_PLUGINS=["apoc"]
    volumes:
      - neo4j_data_tsai:/data
volumes:
  neo4j_data_tsai: